### ISSUE TITLE
Node.js unhandled Promise rejections

### ISSUE THREAD

**Issue by mmarchini** [openjs-foundation/user-feedback#2]
Hey @joesepi, the Node.js project would like to start a survey to collect feedback from the community about unhandled Promise rejections on Node.js. We already crafted the questions, how should we proceed?

**Survey title**
Node.js unhandled Promise rejections

**Survey owner(s)**
Node.js TSC

**Survey timeframe**
Two weeks (evaluate if we have enough answers before the end of it, otherwise extend the survey)

**Survey goals summary**
We want to resolve the unhandled rejections deprecation warning on Node.js, but there's no consensus on which default behavior should be adopted. The TSC will need to vote to decide the default. We decided to collect feedback from the community to better understand use cases, before making a decision.

**Survey questions**
Survey questions were crafted collaboratively on the Node.js TSC repository. The resulting questions are available in the following document: https://github.com/nodejs/TSC/blob/master/surveys/promise-rejections/survey.md

**Comment by joesepi** [comment]
Hello @mmarchini! This is great news as I've been meaning to do some spring cleaning in user feedback. Let me ramp back up on this initiative and get back to you with next steps. Thanks so much!

**Comment by mmarchini** [comment]
Hey @joesepi! Any updates on this survey?

**Comment by joesepi** [comment]
I'm sorry @mmarchini -- we've run up against the OpenJS World event and everyone is swamped with work to execute the event, even me. I have this on my list to move this forward and will try to make progress as soon as I can.

**Comment by jorydotcom** [comment]
@joesepi @mmarchini I'll bring this to the foundation marketing team (including @RRomoff and @rginn) - seems like something we can facilitate there for sure, and will give us a chance to work out this process for future surveys too.

**Comment by mmarchini** [comment]
@jorydotcom Thank you! Do you have an idea of when we would be able to start circulating the survey? We're waiting on the survey for the decision, and we would like to decide before the next major release (which is scheduled for October).

**Comment by mmarchini** [comment]
Hi @jorydotcom, do you have any updates on this? Thanks!

**Comment by joesepi** [comment]
Sorry for this delay. Let's perhaps chat some in Slack to keep it moving.

**Comment by mmarchini** [comment]
Sounds good. Which channel should I join so we can chat?

**Comment by mmarchini** [comment]
The survey is available at: https://www.surveymonkey.com/r/FTJM7YD

We also wrote an accompanying blog post for extra context: https://medium.com/@nodejs/node-js-promise-reject-use-case-survey-98e3328340c9

The survey will run for at least two weeks, at which point we'll evaluate if the number of replies is enough for us to move forward, otherwise we might extend it for a week or two. Please fill out the survey as it will help us decide the future of unhandled promise rejections on Node.js!

**Comment by mmarchini** [comment]
Closing since the survey has been done, the vote happened and a decision was reached.
